version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: blob_postgres
    restart: unless-stopped
    env_file:
      - env-local-sample
    ports:
      - "${POSTGRES_PORT}:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Use vendor directory for Go modules
      args:
        - GOFLAGS=-mod=vendor
    container_name: blob_server
    restart: unless-stopped
    # not needed as the application should read .env file
    # in the /app/.env
    # env_file:
    #   - env-local-sample
    ports:
      - "55555:55555"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./private_key.pem:/app/private_key.pem:ro
      - ./env-local-sample:/app/.env:ro
      - ./db-migrations:/db-migrations:ro

# volumes:
#   pgdata:
